### ISSUE TITLE
Support for partial updates

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/shogun#169]
We should add interfaces for partial updates of entities.

[HTTP `PATCH`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) should be appropriate for this case.

Currently if we have large objects or objects with read-only fields we need to send huge objects and do some crazy workarounds.
When changing just one attribute of an entity, there should be an interface to post only this one changed attribute.

**Comment by dnlkoch** [comment]
Agreed, this would be very helpful!
