### ISSUE TITLE
spring-boot update to v2.4.0 needs adapdations of application.yml files

### ISSUE THREAD

**Issue by annarieger** [terrestris/shogun#191]
With https://github.com/terrestris/shogun/pull/164 the version of `spring-boot` dependency was updated from `2.3.5.RELEASE` to `2.4.0`.

With this change the config file processing in Spring Boot was changed (s. https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4#multi-document-properties-files) so the existing structure of `application.yml` files does't match anymore and customized project settings (e.g. profiles) doesn't get overriden in children projects.

**Comment by dnlkoch** [comment]
Fixed via #348.
